spring.application.name=Gadigo

spring.data.mongodb.uri=mongodb://localhost:27017/gadigo

# JWT Secret and Expiration
jwt.secret=gadigo_super_secret_key_that_should_be_at_least_256_bits_long_for_hs256_algorithm!
jwt.expiration=86400000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
